// generated by tools/embed.py - the web build the shell extracts into Documents/RoguSo/app
#pragma once
#include <cstddef>
struct EmbeddedFile { const char* path; const unsigned char* data; size_t size; };
extern const EmbeddedFile EMBED_FILES[];
extern const int EMBED_COUNT;
extern const char* const EMBED_VERSION;
