// Generates the RoguSo cursor: a voxel golden-fire arrow (quantised to 2px "voxels", white-hot core at the tip
// cooling through gold/amber to ember, a few detached flame voxels off the tail) plus the pressed variant
// (greyed out, nudged 1px down). Writes src/ui/cursor.js with both PNGs as data URIs.
//   node tools/cursor_gen.mjs
import sharp from 'sharp';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const S = 32, V = 2;                       // canvas 32px, voxel 2px
const tip = [3, 3];

// classic arrow silhouette, voxel-quantised: a block is in if its centre is inside the polygon
const inside = (x, y) => {
  const px = x + 0.5, py = y + 0.5;
  // arrow pointing up-left: tip (3,3); left edge straight down to (3,22); in to (10,18); down to (12,26); right up
  // the diagonal back to the tip
  const poly = [[2, 2], [2, 27], [12, 21], [15, 31], [20, 29.5], [16.5, 19], [25, 17]];
  let insidePoly = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i], [xj, yj] = poly[j];
    if ((yi > py) !== (yj > py) && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) insidePoly = !insidePoly;
  }
  return insidePoly;
};

// detached flame voxels off the tail (hand-placed, the "lighting a little" sparks)
const sparks = [[23, 26, 1], [26, 30, 0.8], [20, 30, 0.6], [28, 24, 0.55], [24, 21, 0.45], [27, 28, 0.7]];

function paint(pressed) {
  const raw = Buffer.alloc(S * S * 4, 0);
  const blocks = [];
  for (let by = 0; by < S / V; by++) {
    for (let bx = 0; bx < S / V; bx++) {
      const x = bx * V, y = by * V;
      const hit = inside(x + 1, y + 1);
      if (hit) blocks.push([bx, by, 'body']);
    }
  }
  const has = new Set(blocks.map(([b, a]) => b + ',' + a));
  const set = (bx, by, rgba) => {
    for (let dy = 0; dy < V; dy++) for (let dx = 0; dx < V; dx++) {
      const x = bx * V + dx, y = by * V + dy;
      if (x < 0 || y < 0 || x >= S || y >= S) continue;
      const i = (y * S + x) * 4;
      raw[i] = rgba[0]; raw[i + 1] = rgba[1]; raw[i + 2] = rgba[2]; raw[i + 3] = rgba[3];
    }
  };
  const lerp = (a, b, t) => a + (b - a) * t;
  const shade = (r, g, b, t) => [Math.round(lerp(r, 20, t)), Math.round(lerp(g, 12, t)), Math.round(lerp(b, 8, t)), 255];
  const grey = (r, g, b) => {
    const l = Math.round(r * 0.35 + g * 0.5 + b * 0.15);
    return [Math.round(lerp(l, 96, 0.35)), Math.round(lerp(l, 96, 0.35)), Math.round(lerp(l, 100, 0.35)), 255];
  };
  for (const [bx, by] of blocks) {
    const x = bx * V, y = by * V;
    const d = Math.hypot(x - tip[0], y - tip[1]);
    let c;
    if (d < 4.5) c = [255, 250, 224];                 // white-hot core
    else if (d < 8.5) c = [255, 213, 92];             // gold
    else if (d < 13) c = [255, 156, 44];              // amber
    else if (d < 18) c = [255, 104, 28];              // ember
    else c = [196, 58, 16];                           // deep tail
    const dy = y - tip[1];
    if (dy > 16 && Math.sin(x * 1.7 + y * 0.9) > 0.55) c = [255, 190, 60];   // lick of flame across the tail
    // fire-lit rim on the top-left silhouette, dark outline on the bottom-right, body slightly deepened
    const up = !has.has(bx + ',' + (by - 1)) || !has.has((bx - 1) + ',' + by);
    const dn = !has.has(bx + ',' + (by + 1)) || !has.has((bx + 1) + ',' + by);
    let out = shade(...c, 0.28);
    if (up) out = [Math.min(255, c[0] * 0.55 + 255 * 0.45), Math.min(255, c[1] * 0.55 + 250 * 0.45), Math.min(255, c[2] * 0.55 + 210 * 0.45), 255];
    if (dn) out = shade(...c, 0.62);
    set(bx, by + (pressed ? 0.5 : 0), pressed ? grey(...out) : out);
  }
  for (const [sx, sy, a] of sparks) {
    const c = a > 0.7 ? [255, 214, 96] : [255, 140, 40];
    const out = shade(...c, 0.5);
    set(sx, sy + (pressed ? 0.5 : 0), pressed ? grey(...out) : out);
    set(sx + 1, sy + (pressed ? 0.5 : 0), pressed ? grey(...out) : out);
  }
  return raw;
}

const png = (raw) => sharp(raw, { raw: { width: S, height: S, channels: 4 } }).png().toBuffer();
const a = await png(paint(false));
const b = await png(paint(true));
const uri = (buf) => 'data:image/png;base64,' + buf.toString('base64');
const out = `// The RoguSo cursor, generated by tools/cursor_gen.mjs (do not edit by hand): a voxel golden-fire arrow and its
// pressed (greyed) variant, as data URIs. main.js injects the CSS; the hotspot is the arrow tip.
export const CURSOR = "${uri(a)}";
export const CURSOR_DOWN = "${uri(b)}";
`;
writeFileSync(join(ROOT, 'src/ui/cursor.js'), out);
console.log('cursor.js written:', a.length, b.length, 'bytes');
