#!/usr/bin/env python3
"""Bundle the web game into C++ byte arrays the shell extracts at first run.

    python3 tools/embed.py [version]   # -> build/embed_data.cpp + shell/embed.h + shell/version.h

The version comes from the argument or falls back to the newest CHANGELOG.md entry.
Included: index.html, sword.png, everything under src/ and vendor/.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT_DIR = ROOT / 'build'
OUT = OUT_DIR / 'embed_data.cpp'
HDR = ROOT / 'shell' / 'embed.h'

INCLUDE_FILES = ['index.html', 'sword.png']
INCLUDE_DIRS = ['src', 'vendor']
EXCLUDE_EXT = {'.py', '.md', '.ico', '.log', '.mjs'}


def version() -> str:
    if len(sys.argv) > 1 and sys.argv[1]:
        return sys.argv[1]
    for line in (ROOT / 'CHANGELOG.md').read_text(encoding='utf-8').splitlines():
        if line.startswith('## '):
            m = re.search(r'[0-9]+\.[0-9]+\.[0-9]+', line)
            if m:
                return m.group(0)
    return '0.0.0'


files = []
for name in INCLUDE_FILES:
    p = ROOT / name
    if p.is_file():
        files.append(p)
for d in INCLUDE_DIRS:
    for p in sorted((ROOT / d).rglob('*')):
        if p.is_file() and p.suffix.lower() not in EXCLUDE_EXT:
            files.append(p)


def ident(p: Path) -> str:
    s = str(p.relative_to(ROOT)).replace('\\', '/').replace('.', '_').replace('/', '_')
    return 'F_' + s


out = ['// generated by tools/embed.py - the web build as byte arrays (do not edit by hand)']
out.append('#include "embed.h"')
for p in files:
    data = p.read_bytes()
    arr = ', '.join(str(b) for b in data)
    rel = str(p.relative_to(ROOT)).replace('\\', '/')
    out.append(f'static const unsigned char {ident(p)}[{len(data)}] = {{\n{arr}\n}};')
out.append('const EmbeddedFile EMBED_FILES[] = {')
for p in files:
    rel = str(p.relative_to(ROOT)).replace('\\', '/')
    out.append(f'  {{ "{rel}", {ident(p)}, {p.stat().st_size} }},')
out.append('};')
out.append(f'const int EMBED_COUNT = {len(files)};')
out.append(f'const char* const EMBED_VERSION = "{version()}";')

OUT_DIR.mkdir(exist_ok=True)
OUT.write_text('\n'.join(out), encoding='utf-8')
HDR.write_text(
    '// generated by tools/embed.py - the web build the shell serves straight from memory\n'
    '#pragma once\n'
    '#include <cstddef>\n'
    'struct EmbeddedFile { const char* path; const unsigned char* data; size_t size; };\n'
    'extern const EmbeddedFile EMBED_FILES[];\n'
    'extern const int EMBED_COUNT;\n'
    'extern const char* const EMBED_VERSION;\n',
    encoding='utf-8')
(ROOT / 'shell' / 'version.h').write_text(
    '// generated by tools/embed.py - do not edit by hand\n'
    '#pragma once\n'
    f'#define ROGUSO_VERSION "{version()}"\n'
    f'#define ROGUSO_VERSION_W L"{version()}"\n',
    encoding='utf-8')
total = sum(p.stat().st_size for p in files)
print(f'embedded {len(files)} files, {total / 1e6:.1f} MB, version {version()} -> {OUT.name} + embed.h + version.h')
